### ISSUE TITLE
Add Mill 0.11.0 / 0.11.1 support

### ISSUE THREAD

**Issue by davesmith00000** [DavidGregory084/mill-tpolecat#32]
I feel like I'm being a touch hasty here because Mill 0.11.0 has _just_ been released, but mill-tpolecat therefore need's a new version. :smile: 

Currently 404's because no release:

https://repo1.maven.org/maven2/io/github/davidgregory084/mill-tpolecat_mill0.11_2.13/0.3.2/mill-tpolecat_mill0.11_2.13-0.3.2.pom

Many thanks, love your work. :pray:

**Comment by joan38** [comment]
@DavidGregory084 any idea why the I'm not able to publish `v0.3.3`?
https://github.com/DavidGregory084/mill-tpolecat/actions/runs/5393566279

**Comment by lolgab** [comment]
mill-tpolecat `0.3.5` was release with support for Mill `0.11`.
The issue can be closed.

**Comment by DavidGregory084** [comment]
I'm so sorry @joan38 I must have missed the notification about this!

**Comment by joan38** [comment]
No worries @DavidGregory084 sounds like we managed. Thanks @lolgab !
I had to jump 0.3.4 because CI wouldn't trigger a 2nd time.
